import streamlit as st
import numpy as np
import cv2

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Dropout
)

# Rebuild model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    MaxPooling2D(2, 2),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Flatten(),

    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(1, activation='sigmoid')
])

# Load trained weights
model.load_weights("brain_tumor_weights.weights.h5")

st.title("🧠 Brain Tumor Detection")

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    file_bytes = np.asarray(
        bytearray(uploaded_file.read()),
        dtype=np.uint8
    )

    img = cv2.imdecode(file_bytes, 1)

    st.image(img, caption="Uploaded MRI")

    # Preprocessing
    img = cv2.resize(img, (128, 128))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    # Prediction
    prediction = model.predict(img)
    confidence = float(prediction[0][0])

    st.subheader("Prediction Result")

    if confidence > 0.5:

        st.error("⚠️ Tumor Detected")

        st.progress(int(confidence * 100))

        st.metric(
            label="Confidence",
            value=f"{confidence * 100:.2f}%"
        )

        st.write(f"Raw Prediction Score: {confidence:.4f}")

        st.subheader("🩺 Tumor Information")

        st.info("""
This AI model has detected the possible presence of a brain tumor.

⚠️ Note:
This system can only detect whether a tumor may be present.
It cannot identify the exact tumor type.
Please consult a qualified neurologist or radiologist for medical diagnosis.
""")

        st.markdown("""
### Possible Symptoms
- Persistent headaches
- Nausea and vomiting
- Vision problems
- Seizures
- Memory issues
- Difficulty speaking

### Common Treatment Options
- Surgery
- Radiation Therapy
- Chemotherapy
- Targeted Drug Therapy
- Regular MRI Monitoring

### Recommendations
✅ Consult a neurologist immediately

✅ Get a detailed MRI report reviewed by a specialist

✅ Follow medical advice and treatment plans
""")

    else:

        st.success("✅ No Tumor Detected")

        st.progress(int((1 - confidence) * 100))

        st.metric(
            label="Confidence",
            value=f"{(1 - confidence) * 100:.2f}%"
        )

        st.write(f"Raw Prediction Score: {confidence:.4f}")

        st.info("""
No signs of tumor were detected in the uploaded MRI image.

⚠️ This prediction is generated by an AI model and should not replace professional medical diagnosis.
If symptoms persist, consult a healthcare professional.
""")

# Sidebar
st.sidebar.title("About")

st.sidebar.info(
    """
Brain Tumor Detection using CNN

Developed by Akshay Jadhav | CSE-AIML | GITAM University

Tech Stack:
- Python
- TensorFlow
- OpenCV
- Streamlit
"""
)

# Footer
st.markdown("---")

st.markdown(
    """
<div style='text-align:center'>
🧠 Brain Tumor Detection System<br>
Developed by Akshay Jadhav | CSE-AIML | GITAM University
</div>
""",
    unsafe_allow_html=True
)